project:
  type: website
  output-dir: docs

website:
  title: "OSC_labmeeting_wiedemer_20240624"
  navbar:
    left:
      - href: index.qmd
        text: OSC and CLI Crash Course
      - about.qmd
      - href: page_2.qmd
        text: Software at OSC

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true




